name: butler

permissions:
  contents: read
  pull-requests: write

on:
  issue_comment:
    types:  [created]

jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - name: Show temp script
        run: cat /home/runner/work/_temp/c02dee97-9984-4e6f-b903-7f712a2cb239.sh || echo "File not found"
      - name: Dump GitHub context
        run: echo "${{ toJSON(github) }}"
      - uses: ca-dp/code-butler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Make sure this exists in your secrets!
          cmd: chat
          comment_body: ${{ github.event.comment.body }}
          lang: en             