name: butler

permissions:
  contents: read
  pull-requests: write

on:
  issue_comment:
    types:  [created]

jobs:
  chat:
    runs-on: ubuntu-latest
    steps:
      - uses: ca-dp/code-butler@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }} # Make sure this exists in your secrets!
          cmd: review
#          comment_body: ${{ github.event.comment.body }}
          lang: en             