name: upper-cross
on:
  push:
    paths:
      - ".github/workflows/upper-cross.yml"
      - "upper/**"
  workflow_dispatch: # manual
jobs:
  cross:
    permissions:
      contents: write
    name: capture-job-using-script
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: upper
    steps:
      - uses: actions/checkout@v4
      - name: Make script executable
        run: chmod +x ./build.xplat.sh
      - uses: actions/setup-go@v5
        with:
          go-version: '1.22'
          cache-dependency-path: ./upper/go.sum
      - run: ./build.xplat.sh
      - uses: softprops/action-gh-release@v2
        with:
          files: ./upper/bin/upper*
          body: |
            # upper cross-compiled binaries 
            - Built and uploaded by GitHub Actions hahaha  
          tag_name: ${{github.ref_name}}

