name: upper-build
on:
  push:
    paths:
      - ".github/workflows/upper-build.yml"
      - "upper/**"
  workflow_dispatch: # manual
jobs:
  build:    
    name: do the build
    runs-on: ubuntu-latest
    steps:
      - run: pwd && ls -la
      - uses: actions/checkout@v4
      - run: pwd && ls -la
      - run: go version
      - uses: actions/setup-go@v5
        with:
          go-version:   '1.22'
      - run: go version
